datasource1.url=jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
datasource1.username=sa
datasource1.password=

datasource2.url=jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1
datasource2.username=sa
datasource2.password=

datasource3.url=jdbc:h2:mem:db3;DB_CLOSE_DELAY=-1
datasource3.username=sa
datasource3.password=